- host: "example.com"
  addr: ":8080"
  locations:
    - uri: /test
      target: http://localhost:4444
    - uri: /rest/
      target: http://localhost:4444
    - uri: /best
      target: http://localhost:4444/test
    - uri: /gest
      headers:
        - name: "X-Real-IP"
          value: "{{ .RemoteIp }}"
      target: http://localhost:4444/test
    - uri: /pest/
      target: http://localhost:4444/test/
    - uri: /jest/
      target: http://localhost:4444/test/
- host: example.com
  addr: ":8040"
  locations:
    - uri: /t[de]st
      target: http://localhost:4444
- host: example.com
  addr: ":9000"
  locations:
    - uri: /t[de]st
      target: http://localhost:4444